/*const projects = [
  {
    id: "1",
    title: "Cikao Park Purwakarta",
    detailTitle: "Pintu Masuk Water Park",
    client: "Cikao Park",
    location: "Purwakarta",
    category: "Passenger Gate",
    year: "2019",
    description: `
      Cikao Park merupakan tempat wisata yang menawarkan taman rekreasi air dengan kolam ombak, satwa liar & ilusi optic,
      yang berlokasi di Jatiluhur Purwakarta, menjadikan tempat wisata ini mudah dijangkau dan ramai pengunjung.
      Untuk memudahkan transaksi dan pelaporan dengan baik dan efektif, pengelola Cikao Park memberikan kesempatan kepada
      PT. Surya Teknologi Nasional untuk memasang Sistem Ticketing di tempat tersebut.
    `,
    img: ["/Cikao-Gate.jpeg"],
    detailImg: ["/Cikao-Gate.jpeg", "/Cikao-Gate1.jpg"],
    technologies: ["Laravel", "MySQL", "Bootstrap"],
    features: [
      "Sistem Ticketing Otomatis",
      "Integrasi dengan Barrier Gate",
      "Pelaporan Transaksi Real-Time",
    ],
  },
  {
    id: "2",
    title: "Le Giant Pool & Bar Bali",
    detailTitle: "Pintu Masuk Pool & Bar",
    client: "Le Giant",
    location: "Kuta, Bali",
    category: "Passenger Gate",
    year: "2020",
    description: "Le Giant Pool & Bar merupakan tempat yang menawarkan kolam renang dan resto yang berlokasi di Kuta Bali, menjadikan tempat wisata ini mudah dijangkau dan ramai pengunjung. Untuk memudahkan sistem informasi, pelaporan, perekapan dengan baik dan efektif, pengelola Le Giant Pool & Bar ini memberikan kesempatan kepada PT. Surya Teknologi Nasional untuk pemasangan Flap barrier dengan Sistem Ticketing. Tujuan hal tersebut yaitu untuk memudahakan dalam pelaporan keuangan, pelaporan secara real time dan memudahkan dalam perekapan data. Pada Sistem Ticketing ini terdapat Flap Barrier yang digunakan untuk membatasi para pengunjung untuk lebih tertib, teratur dan terkontrol. Tertib karena setiap orang yang akan masuk hanya diperuntukan bagi orang yang memiliki tiket yang valid (1 tiket hanya berlaku untuk 1 orang), teratur karena orang yang tidak berkepentingan tidak dapat masuk begitu saja ke dalam area Le Giant Pool & Bar, dan terkontrol karena setiap yang masuk ataupun keluar akan terekap datanya secara otomatis dan real time.Pada Sistem Ticketing ini terdapat Flap Barrier yang digunakan untuk membatasi para pengunjung untuk lebih tertib, teratur dan terkontrol. Tertib karena setiap orang yang akan masuk hanya diperuntukan bagi orang yang memiliki tiket yang valid (1 tiket hanya berlaku untuk 1 orang), teratur karena orang yang tidak berkepentingan tidak dapat masuk begitu saja ke dalam area Le Giant Pool & Bar, dan terkontrol karena setiap yang masuk ataupun keluar akan terekap datanya secara otomatis dan real time.",
    img: ["/Pintu Masuk Pool.jpg"],
    detailImg: ["/Pintu Masuk Pool.jpg", "/legiant.png"],
    technologies: ["React", "Firebase"],
    features: ["QR Scan", "Realtime Check-in", "Payment Integration"],
  },
  {
    id: "3",
    title: "RS Permata Cirebon",
    detailTitle: "Rumah Sakit Permata Cirebon",
    client: "Rumah Sakit Permata Cirebon",
    location: "Cirebon, Jawa Barat",
    category: "Parkir Sistem dengan Automatic Barrier Gate",
    year: "2020",
    description: " PT. Surya Teknologi Nasional berkesempatan memasang Peralatan dan Sistem Parkir di Rumah Sakit Permata Cirebon. Sistem parkir yang dipakai yaitu menggunakan sistem manless. Sistem Manless dari PT Surya Teknologi dipakai karena mudah penggunaannya dimana tidak ada operator di pintu masuk. Untuk pemasangan perangkat parkir berada di 2 titik yaitu Pintu Masuk dan Keluar jalan Tuparev serta Pintu Masuk dan Keluar di Jalan Pilang Raya.Untuk pintu masuk manless dari PT Surya Teknologi Nasional pengendara dapat mengambil karcis parkir dan menggunakan kartu parkir. Untuk kendaraan umum, penjenguk pasien dapat mengambil karcis parkir. Pengendara juga tidak perlu khawatir di masa pandemi karena perangkat sudah didukung tombol touchless (Tanpa bersentuhan dengan tombol). Bagi dokter, staff RS, dan pasien terdapat sistem membership yang memungkinkan pendataan menggunakan plat nomor kendaraan dan penggunaan kartu member yang memudahkan ketika akses masuk dan keluar.Sistem Parkir PT. Surya Teknologi Nasional memiliki hasil pelaporan yang real time, dimana Laporan hasil pendapatan akan termuat otomatis oleh software dan langsung terkirim pada PC Server. Laporan ini dapat dicetak atau bisa dilihat secara online melaui jaringan internet.",
    img: ["/RSUD-Permata.jpg"],
    detailImg: ["/RS-CRB.jpg","/RS-CRB1.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"],
  },
 {
    id: "4",
    title: "Perumahan Katapang",
    detailTitle: "Perumahan Katapang Indah Residence",
    client: "Perumahan Katapang Indah Residence",
    location: "Jalan Terusan Kopo, Bandung",
    category: "Automatic Barrier Gate",
    year: "2020",
    description: "Katapang Indah Residence merupakan sebuah perumahan yang berlokasi di Kota Bandung. Untuk meningkatkan keamaanan dan ketertiban di Katapang Indah Residence,pengelola Katapang Indah Residence menerapkan Sistem keamanan dengan memberikan kesempatan kepada PT. Surya Teknologi Nasional untuk memasang Sistem Automatic Barrier Gate pada perumahan tersebut. Konsep Sistem Automatic Barrier Gate di perumahan Katapang Indah Residence menggunakan sistem 2 jalur yaitu akses masuk dan keluar yang bersebelahan dengan pos keamanan di tengahnya, dan dilengkapi juga dengan CCTV untuk mengcapture aktivitas keluar masuk warga pada kawasan Katapang Indah Residence. Sistem Automatic Barrier Gate ini juga mendukung kebutuhan di perumahan Katapang Indah Residence yaitu dengan memberikan fitur expired member, biasanya hal tersebut dibutuhkan jika terdapat warga yang belum membayar iuran, sehingga kartu tidak akan dapat digunakan untuk sementara, sampai status member tersebut kembali aktif. Dengan Sistem Kartu Akses berbasis RFID ini, pengelola dapat melihat history aktivitas keluar masuk warganya secara real time.",
    img: ["/Katapang.jpg"],
    detailImg: ["/Katapang.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"],
 },
 {
   id: "5",
    title: "Perbaikan Sistem RSUD Gunung Jati",
    detailTitle: "Rumah Sakit Daerah Gunung Jati Cirebon",
    client: "RSUD Gunung Jati",
    location: "Kota Cirebon, Jawa Barat",
    category: "Sistem Parkir",
    year: "2020",
    description: "Rumah Sakit Gunung Jati merupakan Rumah Sakit Daerah terbesar di Cirebon, yang terdapat lahan parkir untuk dikelola dengan akses area parkir berbayar. Dengan ini PT. Surya Teknologi Nasional berkesempatan untuk melakukan perbaikan peralatan dan sistem parkir di Rumah Sakit Gunung Jati. Sistem parkir yang dipakai yaitu menggunakan sistem manless. Sistem Manless dari PT Surya Teknologi dipakai karena mudah penggunaannya dimana tidak ada operator di pintu masuk. Untuk pemasangan perangkat parkir berada di 2 titik yaitu Pintu Masuk dan Keluar jalan Sudarsono serta Pintu Masuk dan Keluar di Jalan Kesambi.Pada 2020 kami berkesempatan melakukan perbaikan untuk sistem parkir di RSD Gunung Jati yang merupakan rumah sakit rujukan di kota Cirebon. Untuk kebutuhan parkir di pintu masuk menggunakan sistem manless. Sistem manless dari PT Surya Teknologi Nasional memungkinkan pengendara dapat mengambil karcis parkir tanpa bersentuhan dengan tombol tiket dan menggunakan menggunakan kartu parkir. Untuk kendaraan umum, penjenguk pasien dapat mengambil karcis parkir. Pengendara juga tidak perlu khawatir karena perangkat sudah didukung tombol touchless (Tanpa bersentuhan dengan tombol). Bagi dokter, staff RS, dan pasien terdapat sistem membership yang memungkinkan pendataan menggunakan plat nomor kendaraan dan penggunaan kartu member yang memudahkan ketika akses keluar dan masuk.Sistem Parkir PT. Surya Teknologi Nasional memiliki hasil pelaporan yang real time, dimana Laporan hasil pendapatan akan termuat otomatis oleh software dan langsung terkirim pada PC Server. Laporan ini dapat dicetak atau bisa dilihat secara online melaui jaringan internet.",
    img:["/RSUD.jpg"],
    detailImg: ["/RSUD1.jpeg","/RSUD2.jpg","/RSUD3.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "6",
    title: "Area 52 Studio",
    detailTitle: "Showcase Website Area 52 Studio",
    client: "Area 52 Studio",
    location: "Bandung, jawa Barat",
    category: "Website",
    year: "2017",
    description: "Area 52 merupakan pemasok kebutuhan seni di Kota Bandung. Penjualan utama yaitu Scribblebooks yang sudah terkenal di kalangan seniman. Website yang dibuat bertujuan untuk menunjukan berbagai produk yang dimiliki.",
    img:["/area52studio.png"],
    detailImg: ["/area52studio.png","/Area52.png"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "7",
    title: "Batik Putri Pratiwi",
    detailTitle: "Website Batik Pratiwi",
    client: "Batik Putri Pratiwi",
    location: "Bandung, jawa Barat",
    category: "Website",
    year: "2017",
    description: "Website Penjual Showcase Batik",
    img:["/Batik-Pratiwi.png"],
    detailImg: ["/Batik-Pratiwi.png"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "8",
    title: "Sistem Informasi Perusahaan",
    detailTitle: "Sistem Informasi Perusahaan",
    client: "Sistem Informasi",
    location: "Makassar",
    category: "Sistem Informasi",
    year: "2018",
    description: "Custom Software Development Sistem Kepegawaian (absensi dan penggajian)",
    img:["/CMS.png"],
    detailImg: ["/CMS.png","/CMS1.png"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "9",
    title: "Gor Cinde ITENAS",
    detailTitle: "Gor Cinde ITENAS",
    client: "GOR Cinde Itenas",
    location: "Bandung, Jawa barat",
    category: "Pemasangan Automatic Barrier Gate",
    year: "2020",
    description: "-",
    img:["/GOR-CINDE.jpeg"],
    detailImg: ["/GOR-CINDE.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
    id: "10",
    title: "Ultima Parkir Garut",
    detailTitle: "Ultima Parkir Garut",
    client: "Ultima Kost | Red doorz",
    location: "Garut, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2020",
    description: "Ultima Parkir merupakan sebuah lahan parkir yang berlokasi di Garut, Jawa Barat. PT. Surya Teknologi Nasional berkesempatan memasang Peralatan dan Sistem Parkir di Ultima Parkir. Sistem parkir yang dipakai yaitu menggunakan sistem manless. Sistem Manless dari PT Surya Teknologi dipakai karena mudah penggunaannya dimana tidak ada operator di pintu masuk. Untuk pemasangan perangkat parkir berada di 1 titik yaitu Pintu Masuk dan Keluar yang bersebelahan, dengan pos operator di tengahnya.Untuk pintu masuk manless dari PT Surya Teknologi Nasional pengendara dapat mengambil karcis parkir dan menggunakan kartu parkir. Untuk kendaraan regular atau nonmember dapat mengambil karcis parkir. Pengendara juga tidak perlu khawatir karena perangkat sudah didukung tombol touchless (Tanpa bersentuhan dengan tombol). Bagi pengendara member terdapat sistem membership yang memungkinkan pendataan menggunakan plat nomor kendaraan dan penggunaan kartu member yang memudahkan ketika akses keluar dan masuk.Sistem Parkir PT. Surya Teknologi Nasional memiliki hasil pelaporan yang real time, dimana Laporan hasil pendapatan akan termuat otomatis oleh software dan langsung terkirim pada PC Server. Laporan ini dapat dicetak atau bisa dilihat secara online melaui jaringan internet.",
    img:["/ULTIMA-PG.jpeg"],
    detailImg: ["/ULTIMA-PG.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "11",
    title: "Parkir MAsjid As sa'diah Sumedang",
    detailTitle: "MAsjid As sa'diah Sumedang",
    client: "Masjid As sa'diah",
    location: "Sumedang, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2020",
    description: "-",
    img:["/MESJID-SUMEDANG.jpeg"],
    detailImg: ["/MESJID-SUMEDANG.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "12",
    title: "Cianjur City Park",
    detailTitle: "Pintu Masuk Cianjur City Park",
    client: "Cianjur City Park",
    location: "Cianjur",
    category: "Ticketing",
    year: "2021",
    description: "Cianjur City Park merupakan tempat rekreasi yang berlokasi di Kota Cianjur. Banyak area permainan di tempat ini yang menjadikan area ini ramai, sehingga membutuhkan sistem informasi yang mendukung untuk pengelolaan tempat wisata tersebut agar dapat terpantau secara efektif. Dengan begitu, Cianjur City Park menerapkan Sistem Ticketing di tempatnya, agar aktitivitas pembelian tiket dapat terpantau oleh sistem, sehingga informasi yang dibutuhkan dapat dilihat secara real time.Pada Pintu Masuk yang terintegrasi dengan Sistem Ticketing digunakan Tripod Turnstile yang digunakan untuk membatasi para pengunjung untuk lebih tertib, teratur dan terdata. Tertib karena setiap orang yang akan masuk pada kawasan rekreasi hanya diperuntukan bagi orang yang memiliki tiket yang valid (1 tiket hanya berlaku untuk 1 orang), teratur karena orang yang tidak berkepentingan tidak dapat masuk, dan terdata karena setiap yang masuk ataupun keluar akan terekap datanya secara otomatis dan real time. Tripod Turnstile ini terintegrasi pada Sistem Ticketing PT. Surya Teknologi Nasional dan peralatan seperti RFID dan Scanner sebagai akses untuk masuk dan keluar kawasan. Sistem Ticketing yang digunakan ini memiliki fitur pelaporan yang yang memudahakan dalam Perhitungan Keuangan, Pelaporan secara real time dan memudahkan dalam perekapan data.",
    img:["/Cianjur.jpeg"],
    detailImg: ["/Cianjur.jpeg","/Cianjur1.jpeg","/Cianjur2.jpeg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "13",
    title: "Mentari Permai Residence",
    detailTitle: "Mentari Permai Residence",
    client: "Mentari Permai Residence",
    location: "Ciparai, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2021",
    description: "Mentari Permai Residence merupakan sebuah perumahan yang berlokasi di Kota Bandung. Untuk meningkatkan keamaanan dan ketertiban di Mentari Permai Residence,pengelola Mentari Permai Residence menerapkan Sistem keamanan dengan memberikan kesempatan kepada PT. Surya Teknologi Nasional untuk memasang Sistem Automatic Barrier Gate pada perumahan tersebut. Konsep Sistem Automatic Barrier Gate di perumahan Mentari Permai Residence menggunakan sistem 2 jalur yaitu akses masuk dan keluar yang bersebelahan dengan pos keamanan di tengahnya. Sistem Automatic Barrier Gate ini juga mendukung kebutuhan di perumahan Mentari Permai Residence yaitu dengan memberikan fitur expired member, biasanya hal tersebut dibutuhkan jika terdapat warga yang belum membayar iuran, sehingga kartu tidak akan dapat digunakan untuk sementara, sampai status member tersebut kembali aktif. Dengan Sistem Kartu Akses berbasis RFID ini, pengelola dapat melihat history aktivitas keluar masuk warganya secara real time.",
    img:["/Mentari-depan.jpeg"],
    detailImg: ["/Mentari1.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "15",
    title: "Taman Lalu Lintas",
    detailTitle: "Pintu Masuk dan Keluar Perumahan Mentari Permai Residence",
    client: "Mentari Permai Residence",
    location: "Ciparai, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2021",
    description: "-",
    img:["/GOR-CINDE.jpeg"],
    detailImg: ["/GOR-CINDE.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "16",
    title: "Pelabuhan Angke DKI Jakarta ",
    detailTitle: "Pintu Masuk Pelabuhan Angke DKI Jakarta",
    client: "Pelabuhan Angke DKI Jakarta",
    location: "DKI, Jakarta",
    category: "Tripod Tunstile ",
    year: "2022",
    description: "Pelabuhan Angke melakukan renovasi. Agar semakin moderen maka dibutuhkan tripod turnstile untuk pembatasan akses masuk.PT. Surya Teknologi Nasional berkesempatan untuk memasang Tripod Tunstile di tempat tersebut.",
    img:["/perumangkejkt.jpeg"],
    detailImg: ["/perumangkejkt.jpeg","/perumangkejkt1.png",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "17",
    title: "Pelabuhan Ciwandan Banten",
    detailTitle: "Pintu Masuk Pelabuhan Ciwandan-Banten",
    client: "Pelabuhan Ciwandan Banten",
    location: "Banten, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2022",
    description: "-",
    img:["/Ciwandan1.jpg"],
    detailImg: ["/Ciwandan1.jpg","/Ciwandan2.png","/Ciwandan3.png"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "18",
    title: "Pelabuhan Panjang Banda Lampung ",
    detailTitle: "Pintu Masuk Pelabuhan Panjang Banda Lampung",
    client: "Pelabuhan Panjang Banda Lampung",
    location: "Banda Lampung",
    category: "Automatic Barrier Gate",
    year: "2022",
    description: "-",
    img:["/Lmpng1.jpg"],
    detailImg: ["/Lmpng1.jpg","/Lmpng2.png","/Lmpng3.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "19",
    title: "Perumahan Fajar Cimahi ",
    detailTitle: "Pintu Masuk Perumahan Fajar Cimahi",
    client: "Perumahan Fajar Cimahi",
    location: "Cimahi",
    category: "Automatic Barrier Gate",
    year: "2022",
    description: "-",
    img:["/Cimahi.jpg"],
    detailImg: ["/Cimahi.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "20",
    title: "Air Mancur Sribaduga Purwakarta ",
    detailTitle: "Air Mancur Sribaduga-Purwakarta",
    client: "Air Mancur Sribaduga Purwakarta",
    location: "Purwakarta, Jawa Barat",
    category: "Turnstile dan Ticketing",
    year: "2022",
    description: "Dinas Kepemudaan Olahraga Pariwisata dan Kebudayaan Purwakarta mengelola Air Mancur Sri baduga dan Museum Purwakarta.Untuk memudahkan transaksi, pelaporan, perekapan dengan baik dan efektif, pimpinan Dinas Kepemudaan Olahraga Pariwisata dan Kebudayaan Purwakarta memberikan kesempatan kepada PT. Surya Teknologi Nasional untuk memasang Sistem Ticketing di tempat tersebut.Pada pintu masuk area rekreasi air mancur digunakan Tripod Turnstile yang digunakan untuk membatasi para pengunjung agar lebih tertib, teratur dan terkontrol.Tertib karena setiap orang yang akan masuk pada kawasan air mancur hanya diperuntukan bagi orang yang memiliki tiket yang valid (1 tiket hanya berlaku untuk 1 orang), teratur karena orang yang tidak berkepentingan tidak dapat masuk begitu saja, dan terkontrol karena setiap yang masuk ataupun keluar akan terekap datanya secara otomatis dan real time.Tripod Turnstile ini terintegrasi pada Sistem Ticketing PT. Surya Teknologi Nasional dengan menggunakan RFID dan scanner barcode sebagai akses untuk masuk dan keluar kawasan.",
    img:["/Sribaduga1.jpg"],
    detailImg: ["/Sribaduga1.jpg","/Sribaduga2.png","/Sribaduga3.png"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "21",
    title: "Bamboorasa Bandung ",
    detailTitle: "Bamboorasa-Bandung",
    client: "Bamboorasa Bandung",
    location: "Bandung, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2023",
    description: "Bamboorasa merupakan cafe yang lagi hits karena penggunaan bambu untuk interiornya. Untuk memudahkan perekapan transaksi parkir, pelaporan, perekapan dengan baik dan efektif, management memberikan kesempatan kepada PT. Surya Teknologi Nasional untuk memasang Sistem parkir di tempat tersebut.Pada pintu masuk area digunakan automatic barrier gate dengan sistem manless membatasi para pengunjung agar lebih tertib, teratur dan terkontrol.Automatic Barrier Gate ini terintegrasi pada Sistem Parkir PT. Surya Teknologi Nasional.",
    img:["/Bamboorasa1.jpg"],
    detailImg: ["/Bamboorasa1.jpg","/Bamboorasa2.png","/Bamboorasa3.jpg","/Bamboorasa4.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "22",
    title: "Gedung ABG Bandung ",
    detailTitle: "Gedung ABG Bandung ",
    client: "Gedung ABG Bandung",
    location: "Bandung, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2019",
    description: "-",
    img:["/ABG1.jpg"],
    detailImg: ["/ABG1.jpg","/ABG2.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "23",
    title: "Metro Penthouse Metro Bandung",
    detailTitle: "Metro Penthouse Metro Bandunge",
    client: "Metro Penthouse Metro Bandung",
    location: "Bandung, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2022",
    description: "-",
    img:["/Merto.jpg"],
    detailImg: ["/Merto.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "24",
    title: "Pelabuhan Bengkulu ",
    detailTitle: "Pelabuhan Bengkulu",
    client: "Pelabuhan Bengkulu",
    location: "Bengkulu",
    category: "Automatic Barrier Gate",
    year: "2023",
    description: "-",
    img:["/Bengkulu1.jpg"],
    detailImg: ["/Bengkulu1.jpg","/Bengkulu2.jpg","/Bengkulu3.jpg","/Bengkulu4.jpg","/Bengkulu5.png","/Bengkulu6.png"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "25",
    title: "Pengadilan Militer Bandung ",
    detailTitle: "Pengadilan Militer Bandung",
    client: "Pengadilan Militer Bandung",
    location: "Bandung, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2023",
    description: "Pengadilan Militer II - 09 merupakan Pengadilan Militer yang berlokasi di Kota Bandung.Untuk meningkatkan keamaanan dan ketertiban di Pengadilan Militer, pengurus Pengadilan Militer menerapkan Sistem keamanan dengan memberikan kesempatan kepada PT. Surya Teknologi Nasional untuk memasang Sistem Automatic Barrier Gate pada tempat tersebut. Konsep Sistem Automatic Barrier Gate di Pengadilan Militer menggunakan sistem remote untuk masuk dan keluar di satu jalur.",
    img:["/Pengadilan.jpg"],
    detailImg: ["/Pengadilan.jpg"],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "26",
    title: "Pelabuhan Angke DKI Jakartam ",
    detailTitle: "Pintu Masuk dan Keluar Perumahan Mentari Permai Residence",
    client: "Mentari Permai Residence",
    location: "Ciparai, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2021",
    description: "-",
    img:["/GOR-CINDE.jpeg"],
    detailImg: ["/GOR-CINDE.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "27",
    title: "Pelabuhan Angke DKI Jakartam ",
    detailTitle: "Pintu Masuk dan Keluar Perumahan Mentari Permai Residence",
    client: "Mentari Permai Residence",
    location: "Ciparai, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2021",
    description: "-",
    img:["/GOR-CINDE.jpeg"],
    detailImg: ["/GOR-CINDE.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "28",
    title: "Pelabuhan Angke DKI Jakartam ",
    detailTitle: "Pintu Masuk dan Keluar Perumahan Mentari Permai Residence",
    client: "Mentari Permai Residence",
    location: "Ciparai, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2021",
    description: "-",
    img:["/GOR-CINDE.jpeg"],
    detailImg: ["/GOR-CINDE.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "29",
    title: "Pelabuhan Angke DKI Jakartam ",
    detailTitle: "Pintu Masuk dan Keluar Perumahan Mentari Permai Residence",
    client: "Mentari Permai Residence",
    location: "Ciparai, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2021",
    description: "-",
    img:["/GOR-CINDE.jpeg"],
    detailImg: ["/GOR-CINDE.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "30",
    title: "Pelabuhan Angke DKI Jakartam ",
    detailTitle: "Pintu Masuk dan Keluar Perumahan Mentari Permai Residence",
    client: "Mentari Permai Residence",
    location: "Ciparai, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2021",
    description: "-",
    img:["/GOR-CINDE.jpeg"],
    detailImg: ["/GOR-CINDE.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
  {
   id: "31   ",
    title: "Pelabuhan Angke DKI Jakartam ",
    detailTitle: "Pintu Masuk dan Keluar Perumahan Mentari Permai Residence",
    client: "Mentari Permai Residence",
    location: "Ciparai, Jawa Barat",
    category: "Automatic Barrier Gate",
    year: "2021",
    description: "-",
    img:["/GOR-CINDE.jpeg"],
    detailImg: ["/GOR-CINDE.jpeg",],
    technologies: ["IoT", "Node.js"],
    features: ["License Plate Recognition", "Remote Access"], 
  },
];

export default projects;*/
